name: PR Summary (Native)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract PR Info
        id: extract
        run: |
          echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "additions=${{ github.event.pull_request.additions }}" >> $GITHUB_OUTPUT
          echo "deletions=${{ github.event.pull_request.deletions }}" >> $GITHUB_OUTPUT
          echo "changed_files=${{ github.event.pull_request.changed_files }}" >> $GITHUB_OUTPUT

      - name: Post PR Summary as Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "🔎 GitHub Native PR Summary"
          message: |
            ## PR Summary (GitHub Native)
            - Title: **${{ steps.extract.outputs.title }}**
            - Author: @${{ steps.extract.outputs.author }}
            - Files Changed: ${{ steps.extract.outputs.changed_files }}
            - Additions: ${{ steps.extract.outputs.additions }}
            - Deletions: ${{ steps.extract.outputs.deletions }}
